src/PokemonGOWeb/Models/PokemonTypeVM.cs
using PokemonGOCore.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PokemonGOWeb.Models
{
    public class PokemonTypeVM
    {
        public int Id { get; set; }

        public string Description { get; set; }

        public PokemonTypeVM(PokemonType pokemonType)
        {
            this.Id = pokemonType.Id;
            this.Description = pokemonType.Description;
        }
    }
}

src/PokemonGOWeb/Models/PokemonViewModel.cs
using PokemonGOCore.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PokemonGOWeb.Models
{
    public class PokemonViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string ImagePath { get; set; }

        public bool CurrentHave { get; set; }

        public int PokemonTypeId { get; set; }
        public PokemonTypeVM PokemonType { get; set; }

        public PokemonViewModel()
        {

        }

        public PokemonViewModel(Pokemon pokemon)
        {
            this.Id = pokemon.Id;
            this.Name = pokemon.Name;
            this.ImagePath = pokemon.ImagePath;
            this.CurrentHave = pokemon.CurrentHave;
            this.PokemonType = new PokemonTypeVM(pokemon.PokemonType);
        }
    }
}

src/PokemonGOWeb/Controllers/HomeController.cs
using PokemonGOCore.Service;
using System.Collections.Generic;
using System.Web.Mvc;

namespace PokemonGOWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

src/PokemonGOWeb/Controllers/PokemonController.cs
using PokemonGOCore.Model;
using PokemonGOCore.Service;
using PokemonGOWeb.Models;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Linq;

namespace PokemonGOWeb.Controllers
{
    public class PokemonController : Controller
    {
        public ActionResult Index()
        {
            var service = new PokemonService();
            List<Pokemon> allPokemons = service.FindAll();

            //ToDo: Passar o allPokemons para a view model
            //Opcional: Criar uma view model para passar para a tela ao invés de passar a model do banco
            List<PokemonViewModel> allPokemonsVms = (from x in allPokemons select new PokemonViewModel(x)).ToList();

            return View(allPokemonsVms);
        }

        [HttpPost]
        public ActionResult Index(string searchString)
        {
            var service = new PokemonService();
            List<Pokemon> filterPokemons = service.FindByText(searchString);
            List<PokemonViewModel> allPokemonsVms = (from x in filterPokemons select new PokemonViewModel(x)).ToList();
            return PartialView("_PartialList_Pokemons", allPokemonsVms);
        }

        public ActionResult Search(string word)
        {
            return View("Index");
        }

        public ActionResult Create()
        {
            var serviceType = new PokemonTypeService();
            List<PokemonType> allTypes = serviceType.FindAll();

            ViewBag.TypesPoke = new SelectList(allTypes, "Id", "Description");
            return View();
        }

        public ActionResult Delete(int? id)
        {
            var service = new PokemonService();
            Pokemon pokemon = service.FindById((int)id);

            PokemonViewModel poker = new PokemonViewModel(pokemon);
            return View(poker);
        }

        [HttpPost]
        public JsonResult Capture(int id)
        {
            var service = new PokemonService();

            var pokemon = service.FindById(id);
            pokemon.Capture();

            service.Update(pokemon);
            return Json(new
            {
                result = pokemon.CurrentHave,
                success = true
            },
               JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Create(PokemonViewModel pokemon)
        {
            var service = new PokemonService();

            Pokemon poker = new Pokemon()
            {
                Name = pokemon.Name,
                ImagePath = pokemon.ImagePath,
                CurrentHave = pokemon.CurrentHave,
                PokemonTypeId = pokemon.PokemonTypeId
            };

            service.Create(poker);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult AjaxDelete(int id)
        {
            var service = new PokemonService();
            Pokemon pokemon = service.FindById(id);
            service.Delete(pokemon);

            return Json(new
            {
                result = pokemon.CurrentHave,
                success = true
            },
              JsonRequestBehavior.AllowGet);
        }
    }
}

src/PokemonGOWeb/Controllers/PokemonTypeController.cs
using System.Web.Mvc;

namespace PokemonGOWeb.Controllers
{
    public class PokemonTypeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Search(string word)
        {
            return View("Index");
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Update()
        {
            return View();
        }

        public ActionResult Delete()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Save(int id)
        {
            return View("Index");
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            return View("Index");
        }
    }
}

src/PokemonGOWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<h1>Seja bem-vindo</h1>
<div>
    <div>
        <img src="~/Content/images/001.png" />
        <img src="~/Content/images/002.png" />
        <img src="~/Content/images/003.png" />
        <img src="~/Content/images/004.png" />
        <img src="~/Content/images/005.png" />
        <img src="~/Content/images/006.png" />
        <img src="~/Content/images/007.png" />
        <img src="~/Content/images/008.png" />
        <img src="~/Content/images/009.png" />
    </div>
    <p>Você deseja ser um mestre pokémon e para isso resolveu criar um sistema para cadastrar os pokémons e marcar quais já conseguiu pegar em sua jornada.</p>
    <p>Algumas funcionalidades já estão prontas e o HTML das telas estão criados, porém estáticos.</p>
    <p>Existe um banco de dados criado com duas tabelas: Pokémon e PokémonType. Seu objetivo é terminar as seguintes tarefas, indo da mais prioritária para a menos prioritária:</p>
    <ul>
        <li>
            1 - Transformar a tela de listagem de pokémons, lendo os dados do banco de dados, listando-os, e mantendo o mesmo layout já criado.
            <ul>
                <li><strong>Opcional</strong>: Se possível, transforme a listagem em uma partial view.</li>
            </ul>
        </li>
        <li>
            2 - Finalizar o cadastro de pokémons. A view já está criada, porém estática.
            <ul>
                <li>
                    Os tipos de Pokémon devem ser carregados do banco de dados (uma tabela já está criada e populada). Não é necessário criar uma tela para cadastrar tipos de Pokémon
                </li>
                <li>
                    O Pokémon deve ser salvo no banco de dados, com o caminho da imagem (há algumas imagens dentro do projeto).
                </li>
            </ul>
        </li>
        <li>
            3 - Implementar a funcionalidade de busca de pokémons. Usuário poderá digitar o nome e filtrar a listagem.
            <ul><li><strong>Opcional</strong>: Execute a busca utilizando javascript e ajax.</li></ul>
        </li>
        <li>
            4 - Implementar a funcionalidade de marcar um pokémon como obtido. Existe um botão para indicar se o usuário possui ou não o pokémon.
            <ul><li><strong>Opcional</strong>: Implemente utilizando javascript e ajax.</li></ul>
        </li>
        <li>
            5 - Implementar a funcionalidade de excluir um pokémon.
            <ul><li><strong>Opcional</strong>: Implemente utilizando javascript e ajax.</li></ul>
        </li>
    </ul>
    <p>A arquitetura do projeto está descrita abaixo. Siga-a!</p>
    <p><img src="~/Content/images/pokemonarch.jpg" /></p>


</div>
<div class="text-center">





    
</div>

src/PokemonGOWeb/Views/Pokemon/Create.cshtml
@model PokemonGOWeb.Models.PokemonViewModel
@{
    ViewBag.Title = "Criar Pokémon";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Criar Pokémon</h2>

<form method="post" action="/Pokemon/Create">
    <div class="form-group">
        <label>Nome</label>
        <input type="text" name="Name" id="Name" class="form-control" placeholder="Inserir o nome">
    </div>
    <div class="form-group">
        <label>Imagem</label>
        <input type="text" name="ImagePath" id="ImagePath" class="form-control" placeholder="Caminho da imagem">
        <small id="fileHelp" class="form-text text-muted">O caminho da imagem deve ser no padrão "~/Content/images/001.png".</small>
    </div>

    <div class="form-group">
        <label for="exampleSelect1">Tipo de Pokémon</label>
        @*<select class="form-control" name="PokemonTypeId" id="PokemonTypeId">
            <option value="1">Elétrico</option>
            <option value="2">Grama</option>
            <option value="3">Fogo</option>
        </select>*@
        @Html.DropDownList("PokemonTypeId", ViewBag.TypesPoke as SelectList, new { @class = "form-control" })
    </div>
    <button type="button" class="btn">Voltar</button>
    <button type="submit" class="btn btn-primary">Salvar</button>
</form>

src/PokemonGOWeb/Views/Pokemon/Delete.cshtml
@model PokemonGOWeb.Models.PokemonViewModel
@{
    ViewBag.Title = "Excluir Pokémon";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/jquery-3.1.0.js"></script>
<script type="text/javascript">

    $(document).ready(function () {
        $('#btnDelete').click(function () {
         
            alert('ok');
            $.ajax({
                type: "post",
                url: "@Url.Action("AjaxDelete", "Pokemon")",
            
                data: { id: '@Model.Id' },
                success: function () {

                    alert("success");

                    // Perform redirect
                    window.location.replace('@Url.Action("Index", "Pokemon")');
                },
                error: function (data) {
                    alert(data.x);
                }
            });
        });
    });
</script>
<h2>Excluir Pokémon</h2>

<form>

    <div class="form-group">
        <img src="http://assets.pokemon.com/assets/cms2/img/pokedex/detail/025.png" class="img-rounded">
    </div>

    <div class="form-group">
        <label>Nome: @Model.Name</label>
    </div>
    <div class="form-group">
        <label>Possui Pokémon: @(Model.CurrentHave ? "sim" : "não")</label>
    </div>
    <div class="form-group">
        <label>Tipo de Pokémon: @Model.PokemonType.Description</label>
    </div>
    <button id="btnDelete" type="button" class="btn btn-primary">Excluir</button>
</form>

src/PokemonGOWeb/Views/Pokemon/Index.cshtml
@model IEnumerable<PokemonGOWeb.Models.PokemonViewModel> 
@{
    ViewBag.Title = "Pokémons";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/jquery-3.1.0.js"></script>
<h2>Pokémons</h2>
<script type="text/javascript">
    $(document).ready(function () {
        $('#btnCreate').click(function () {

            // window.location.reload();
        });

        $('.glyphicon').click(function (event) {
           
            var id = $(this).attr('data-id');  
            
            $.ajax({
                type: 'POST',
                contentType: "application/json; charset=utf-8",
                url: '@Url.Content("Pokemon/Capture")',
                data: "{'id':'" + id + "'}",
                async: false,
                success: function (response) {
                    var obj = $.parseJSON(JSON.stringify(response));
                    if (obj.result) {
                       
                        $(this).removeClass("glyphicon-unchecked");
                        $(this).addClass("glyphicon-check");
                    } else {
                        $(this).addClass("glyphicon-unchecked");
                        $(this).removeClass("glyphicon-check");
                    }
                    alert("Success");
                },

                error: function () { alert("error"); }
            });
        });

        $('#Button1').click(function () {
          
            $.ajax({
                type: 'POST',
                contentType: "application/json; charset=utf-8",
                url: '@Url.Content("Pokemon/Index")',
                data: "{'searchString':'" + document.getElementById('searchString').value + "'}",
               
                success: function (response) {
                    alert("Success");
                    $("#PartialView").html(response);
                  
                },
                error: function () { alert("error"); }
            });

        });
    });

   
</script>

<div class="row">
    <div class="col-lg-3">
        <button id="btnCreate" onclick="location.href='@Url.Action("Create", "Pokemon")';return false;" type="button" class="btn btn-info">Criar Pokémon</button>
    </div>
</div>
<br />
<div class="row">
    <div class="col-lg-3">
        <input id="searchString" type="text" class="form-control left">
    </div>
    <div class="col-lg-3">
        <button id="Button1" type="button" class="btn btn-default left">Buscar</button>
    </div>
</div>
<div id="PartialView">
    @Html.Partial("_PartialList_Pokemons", Model)
</div>

src/PokemonGOWeb/Views/Pokemon/Update.cshtml
@{
    ViewBag.Title = "Editar Pokémon";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar Pokémon</h2>

<form>
    <div class="form-group">
        <img src="http://assets.pokemon.com/assets/cms2/img/pokedex/detail/025.png" class="img-rounded">
    </div>
    <div class="form-group">
        <label>Alterar o nome</label>
        <input type="text" class="form-control" value="Pikachu">
    </div>
    <div class="form-group">
        <label for="exampleInputFile">Defina uma nova imagem</label>
        <input type="file" class="form-control-file" id="exampleInputFile" aria-describedby="fileHelp">
        <small id="fileHelp" class="form-text text-muted">Insira a imagem do Pokémon, porém não poderá ser maior que 4 MB.</small>
    </div>
    <fieldset class="form-group">
        <label>Já possuo o Pokémon?</label>
        <div class="form-check">
            <label class="form-check-label">
                <input type="radio" class="form-check-input" name="optionsRadios" id="optionsRadios1" value="option1" checked>
                Sim
            </label>
        </div>
        <div class="form-check">
            <label class="form-check-label">
                <input type="radio" class="form-check-input" name="optionsRadios" id="optionsRadios2" value="option2">
                Não
            </label>
        </div>
    </fieldset>
    <div class="form-group">
        <label for="exampleSelect1">Tipo de Pokémon</label>
        <select class="form-control" id="exampleSelect1">
            <option selected>Elétrico</option>
            <option>Grama</option>
            <option>Fogo</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Salvar</button>
</form>

src/PokemonGOWeb/Views/Pokemon/_PartialList_Pokemons.cshtml
@model IEnumerable<PokemonGOWeb.Models.PokemonViewModel> 
<table class="table table-striped">
    <thead>
        <tr>
            <th>#</th>
            <th>Imagem</th>
            <th>Nome</th>
            <th>Tipo</th>
            <th>Capturado</th>
            <th>Excluir</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var poker in Model)
        {
            <tr>
                <td>@poker.Id</td>
                <td><img src="~/Content/images/007.png" style="max-height: 30px;" /></td>
                <td>@poker.Name</td>
                <td>@poker.PokemonType.Description</td>
                <td><span class="glyphicon @(poker.CurrentHave ? "glyphicon-check" : "glyphicon-unchecked")" data-id="@poker.Id" style="cursor:pointer;"></span></td>
                <td><span class="glyphicon glyphicon-remove" onclick="location.href='@Url.Action("Delete", "Pokemon", new { id = poker.Id })'" style="cursor:pointer;"></span></td>
            </tr>
        }
        @*<tr>
                <td>1</td>
                <td><img src="~/Content/images/007.png" style="max-height: 30px;" /></td>
                <td>Squirtle</td>
                <td>Água</td>
                <td><span class="glyphicon glyphicon-unchecked" style="cursor:pointer;"></span></td>

                <td><span class="glyphicon glyphicon-remove" onclick="location.href='@Url.Action("Delete", "Pokemon")'" style="cursor:pointer;"></span></td>
            </tr>
            <tr>
                <td>2</td>
                <td><img src="~/Content/images/001.png" style="max-height: 30px;" /></td>
                <td>Bulbasaur</td>
                <td>Grama</td>
                <td><span class="glyphicon glyphicon-check" style="cursor:pointer;"></span></td>

                <td><span class="glyphicon glyphicon-remove" onclick="location.href='@Url.Action("Delete", "Pokemon")'" style="cursor:pointer;"></span></td>
            </tr>
            <tr>
                <td>3</td>
                <td><img src="~/Content/images/004.png" style="max-height: 30px;" /></td>
                <td>Charmander</td>
                <td>Fogo</td>

                <td><span class="glyphicon glyphicon-unchecked" style="cursor:pointer;"></span></td>
                <td><span class="glyphicon glyphicon-remove" onclick="location.href='@Url.Action("Delete", "Pokemon")'" style="cursor:pointer;"></span></td>
            </tr>*@
    </tbody>
</table>

src/PokemonGOWeb/Views/PokemonType/Create.cshtml
@{
    ViewBag.Title = "Criar Tipo de Pokémon";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Criar novo tipo de Pokémon</h2>

<form>
    <div class="form-group">
        <input type="text" class="form-control" placeholder="Insira uma nova descrição">
    </div>
    <button type="submit" class="btn btn-primary">Salvar</button>
</form>

src/PokemonGOWeb/Views/PokemonType/Delete.cshtml
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

src/PokemonGOWeb/Views/PokemonType/Index.cshtml
@{
    ViewBag.Title = "Tipos de Pokémon";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Tipos de Pokemon</h2>

<form class="form-inline">
    <button type="button" class="btn btn-info" onclick="location.href='@Url.Action("Create", "PokemonType")'">Criar novo tipo de Pokémon</button>
    <div class="form-group">
        <input type="text" class="form-control">
    </div>
    <button type="submit" class="btn btn-default">Buscar</button>
</form>
<table class="table table-striped" style="width:50%">
    <thead>
        <tr>
            <th>#</th>
            <th>Description</th>
            <th>Editar</th>
            <th>Excluir</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>Elétrico</td>
            <td><span class="glyphicon glyphicon-pencil" onclick="location.href='@Url.Action("Update", "PokemonType")'" style="cursor:pointer;"></span></td>
            <td><span class="glyphicon glyphicon-remove" onclick="location.href='@Url.Action("Delete", "PokemonType")'" style="cursor:pointer;"></span></td>
        </tr>
        <tr>
            <td>2</td>
            <td>Grama</td>
            <td><span class="glyphicon glyphicon-pencil" onclick="location.href='@Url.Action("Update", "PokemonType")'" style="cursor:pointer;"></span></td>
            <td><span class="glyphicon glyphicon-remove" onclick="location.href='@Url.Action("Delete", "PokemonType")'" style="cursor:pointer;"></span></td>
        </tr>
        <tr>
            <td>3</td>
            <td>Fogo</td>
            <td><span class="glyphicon glyphicon-pencil" onclick="location.href='@Url.Action("Update", "PokemonType")'" style="cursor:pointer;"></span></td>
            <td><span class="glyphicon glyphicon-remove" onclick="location.href='@Url.Action("Delete", "PokemonType")'" style="cursor:pointer;"></span></td>
        </tr>
    </tbody>
</table>

src/PokemonGOWeb/Views/PokemonType/Update.cshtml
@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Update</h2>

src/PokemonGOWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - POD Moss Applications</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Pokémon GO", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Pokémon", "Index", "Pokemon")</li>                    
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - POD Moss Applications - <img src="http://www.corpbusiness.com.br/_img/conteudo/noticia/13108/080514_102541.jpg" style="width:30px;" /></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>